services:
  postgres:
    image: postgres:16-alpine
    container_name: nestjs-modular-prisma-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nestjs_modular
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nest -d nestjs_modular']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
