services:
  postgres:
    image: postgres:16-alpine
    container_name: nestjs-modular-prisma-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nestjs_modular
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nest -d nestjs_modular']
      interval: 5s
      timeout: 3s
      retries: 10

  postgres-test:
    image: postgres:16-alpine
    container_name: nestjs-modular-prisma-postgres-test
    profiles:
      - test
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nestjs_modular_test
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nest -d nestjs_modular_test']
      interval: 5s
      timeout: 3s
      retries: 10

  localstack:
    image: localstack/localstack:3
    container_name: nestjs-modular-prisma-localstack
    profiles:
      - localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: dynamodb
      AWS_DEFAULT_REGION: us-east-1
      PERSISTENCE: '1'
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -fs http://localhost:4566/_localstack/health | grep dynamodb',
        ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
  postgres_test_data:
  localstack_data:
